"use client";
import React from "react";
import "./globals.css";
import { Roboto } from "next/font/google";
import Aside from "@/Components/Aside";
import Header from "@/Components/Header";
import { Provider } from "react-redux";
import { store } from "../../system";

const roboto = Roboto({ subsets: ["latin"], weight: "500" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Provider store={store}>
					<Aside />
					<Header />
					{children}
				</Provider>
			</body>
		</html>
	);
}
